version: "3"
services:
  api:
    image: tempsens-api
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8000
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - ${PORT}:8001
    volumes:
      - postgresql:/var/lib/postgresql/api
      - postgresql_data:/var/lib/postgresql/api/data
volumes:
  postgresql: {}
  postgresql_data: {}